name: Allure Report
run-name: ${{ github.actor }} is creating Allure report 🚀

on: [push]

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven

      - name: Create .env file
        run: |
          touch src/test/resources/.env
          echo "BASE_URL=${{ secrets.BASE_URL }}" > src/test/resources/.env
          echo "API_KEY=${{ secrets.API_KEY }}" >> src/test/resources/.env
          cat src/test/resources/.env

      - name: Run Test
        run: ./mvnw test
        continue-on-error: true

      - name: Setup Allure History
        uses: actions/checkout@v4.2.2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
